version: "3" 

# If you have problems starting due to corruption add --hard-replay-blockchain to the command
# Seems not to work: --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin

services:
  nodeosd:
    container_name: nodeosd
    image: eosio/eos-dev
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888  --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin --access-control-allow-origin=* --contracts-console --http-validate-host=false
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose: 
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./contracts:/contracts/usr
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    container_name: keosd
    image: eosio/eos-dev
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ./contracts:/contracts/usr
    stop_grace_period: 10m

volumes:
  nodeos-data-volume:
  keosd-data-volume:
